logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(filename)s | %(funcName)s | %(levelname)s: %(message)s'
    verbose:
      format: '%(asctime)s %(module)-10s|%(lineno)-3d %(levelname)-8s %(message)s'
      datefmt: '%Y-%m-%dT%H:%M:%S%z'
    http:
      format: '%(message)s'
  handlers:
    stderr:
      class: logging.StreamHandler
      formatter: simple
      level: WARNING
      stream: ext://sys.stderr
    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: verbose
      filename: src/logs/app.log
      maxBytes: 50000
      backupCount: 2
    debug:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
    http_file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: http
      filename: src/logs/requests.log
      maxBytes: 10000
      backupCount: 1
  loggers:
    root:
      level: INFO
      handlers:
      - stderr
      - file
    debug:
      level: DEBUG
      handlers:
      - debug
      propagate: false
    http:
      level: DEBUG
      handlers:
      - http_file
      propagate: false
    # uvicorn:
    #   handlers:
    #   - file
    #   - debug
    #   incremental: true
database:
  host: localhost
  port: 5432
  database: postgres
assistant:
  implementation: obj  # llama, llama_mock, obj, mock
  